AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  astrace-natal-chart-gen

  Sample SAM Template for astrace-natal-chart-gen

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 240
    Layers:
      - arn:aws:lambda:us-east-1:190891843015:layer:chart_generation_dependencies:3
    Environment:
      Variables:
        BUCKET_NAME: astrace-natal-chart-gen-prototype

Resources:
  NatalChartGenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: natal_chart_gen/
      Handler: app.lambda_handler
      Runtime: python3.9
      Policies:
        # give access to necessary logs
        - Version: "2012-10-17"
          Statement: 
          - Effect: "Allow"
            Action: 
              - "logs:CreateLogGroup"
            Resource: 'arn:aws:logs:us-east-1:190891843015:*'
        - Version: "2012-10-17"
          Statement: 
          - Effect: "Allow"
            Action: 
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: "arn:aws:logs:us-east-1:190891843015:log-group:/aws/lambda/generateChart:*"
        # give access to S3 bucket for reading planet image files
        - Version: "2012-10-17"
          Statement: 
          - Effect: "Allow"
            Action: 
              - "s3:Get*"
            Resource: "arn:aws:s3:::astrace-natal-chart-gen-prototype/images/*"
      Architectures:
        - x86_64
      Events:
        NatalChartGen:
          Type: Api
          Properties:
            Path: /generateChart
            Method: post

Outputs:
  NatalChartGenApi:
    Description: "API Gateway endpoint URL for Prod stage for Generate Chart function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generateChart/"
  NatalChartGenFunction:
    Description: "Generate Chart Lambda Function ARN"
    Value: !GetAtt NatalChartGenFunction.Arn
  NatalChartGenFunctionIamRole:
    Description: "Implicit IAM Role created for Generate Chart function"
    Value: !GetAtt NatalChartGenFunctionRole.Arn
