name: Build Lambda Layer

# only run when there's a change to `requirements.txt`
on:
  pull_request:
    branches: main
    paths:
      - '.github/workflows/package-python-deps-aws-layer.yml'
      - '**/natal_chart_gen/requirements.txt'
  push:
    branches: main
    paths:
      - '.github/workflows/package-python-deps-aws-layer.yml'
      - '**/natal_chart_gen/requirements.txt'

jobs:
  
  deploy:
    name: Package Python Dependencies and Upload Layer to AWS Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Zip it all up and upload to S3
        env:
          release_bucket: python-dependencies-as-lambda-layers
          release_bucket_uri: s3://python-dependencies-as-lambda-layers
          release_id: ${{ format('{0}.zip', github.sha )}}
          release_layer: ${{ format('{0}', github.sha )}}
        run: |
          mkdir python
          # see: https://aws.amazon.com/premiumsupport/knowledge-center/lambda-python-package-compatible/
          pip install \
            --platform manylinux2014_x86_64 \
            --target=python \
            --implementation cp \
            --python 3.9 \
            --only-binary=:all: --upgrade \
            --requirement natal_chart_gen/requirements.txt
          echo building release $release_id
          # zip it up
          zip --quiet -r $release_id python
          
          # copy the file to S3 and install it in lambda layers
          aws s3 cp $release_id $release_bucket_uri
          aws lambda publish-layer-version \
            --layer-name $release_layer \
            --content S3Bucket=$release_bucket,S3Key=$release_id \
            --compatible-runtimes python3.9
